//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevOpsGuys.Vsix.Explorer.OctopusDeploy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevOpsGuys.Vsix.Explorer.OctopusDeploy.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Octopus Deploy Server Settings.
        /// </summary>
        public static string EditSettingsButtonText {
            get {
                return ResourceManager.GetString("EditSettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to automatically populate your Octopus Deploy projects..
        /// </summary>
        public static string ExceptionStartMessage {
            get {
                return ResourceManager.GetString("ExceptionStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered: ODE1001: Octopus Deploy API settings required..
        /// </summary>
        public static string ODE1001 {
            get {
                return ResourceManager.GetString("ODE1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered: ODE1002:.
        /// </summary>
        public static string ODE1002 {
            get {
                return ResourceManager.GetString("ODE1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered: ODE1003: Octopus Deploy explorer will currently only work against version 2.6 and above of Octopus Deploy.
        /// </summary>
        public static string ODE1003 {
            get {
                return ResourceManager.GetString("ODE1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered: ODE1004: You must be logged in to perform this action. Please provide a valid Octopus Deploy API key..
        /// </summary>
        public static string ODE1004 {
            get {
                return ResourceManager.GetString("ODE1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered: ODE1005: Octopus Deploy API returned an invalid response. Check the Octopus Deploy Server Url setting..
        /// </summary>
        public static string ODE1005 {
            get {
                return ResourceManager.GetString("ODE1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error was encountered: ODE1006: Unable to connect to the Octopus Deploy server..
        /// </summary>
        public static string ODE1006 {
            get {
                return ResourceManager.GetString("ODE1006", resourceCulture);
            }
        }
    }
}
